# Generated by Django 5.2 on 2025-06-01 06:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DienVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên diễn viên')),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
            ],
            options={
                'verbose_name_plural': 'Thể loại',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('avatar', models.ImageField(blank=True, default='img/logo.jpg', null=True, upload_to='users/avatars/', verbose_name='Ảnh đại diện')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Nhân viên')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maphim', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã phim')),
                ('ten_phim', models.CharField(max_length=200, verbose_name='Tên phim')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Link trailer')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Link video')),
                ('mo_ta', models.TextField(verbose_name='Mô tả phim')),
                ('dao_dien', models.CharField(max_length=200, verbose_name='Đạo diễn')),
                ('ngay_phat_hanh', models.DateField(blank=True, null=True, verbose_name='Ngày phát hành')),
                ('thoi_luong', models.PositiveIntegerField(help_text='Thời lượng phim tính bằng phút', verbose_name='Thời lượng')),
                ('anh_bia', models.ImageField(blank=True, null=True, upload_to='phim/anhbia/', verbose_name='Ảnh bìa')),
                ('trang_thai', models.CharField(choices=[('sap_chieu', 'Sắp Chiếu'), ('dang_chieu', 'Đang Chiếu'), ('da_ket_thuc', 'Đã Kết Thúc')], default='sap_chieu', max_length=20, verbose_name='Trạng thái')),
                ('luot_xem', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('dien_vien', models.ManyToManyField(related_name='movies', to='myapp.dienvien', verbose_name='Diễn viên')),
                ('the_loai', models.ManyToManyField(related_name='movies', to='myapp.theloai', verbose_name='Thể loại')),
            ],
            options={
                'ordering': ['-ngay_phat_hanh'],
            },
        ),
        migrations.CreateModel(
            name='LichSuXem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='myapp.movie', verbose_name='Phim')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm đánh giá')),
                ('binh_luan', models.TextField(verbose_name='Bình luận')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('phim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.movie', verbose_name='Phim')),
            ],
            options={
                'ordering': ['-ngay_danh_gia'],
                'constraints': [models.UniqueConstraint(fields=('user', 'phim'), name='unique_review_per_user')],
            },
        ),
    ]
