# Generated by Django 5.2 on 2025-07-08 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='diem',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm đánh giá'),
        ),
    ]
