# Generated by Django 5.1 on 2025-04-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_movie_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='img/logo.jpg', null=True, upload_to='users/avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
