# Generated by Django 5.2 on 2025-04-19 06:04

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
