# Generated by Django 5.2 on 2025-04-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_movie_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='search_vector',
        ),
    ]
